### ISSUE TITLE
VSCode 版本兼容问题

### ISSUE THREAD

**Issue by CoderSerio** [mmdctjj/react-syntax-plus#1]
![image](https://github.com/user-attachments/assets/a2f75d0b-0665-4ebc-98cc-169f3eafcf9f)

如图所示，似乎存在版本兼容问题？

**Comment by mmdctjj** [comment]
谢谢反馈，我尽快修复这个问题

**Comment by mmdctjj** [comment]
> ![image](https://private-user-images.githubusercontent.com/79406469/363537430-a2f75d0b-0665-4ebc-98cc-169f3eafcf9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjg5NjMsIm5iZiI6MTcyNTMyODY2MywicGF0aCI6Ii83OTQwNjQ2OS8zNjM1Mzc0MzAtYTJmNzVkMGItMDY2NS00ZWJjLTk4Y2MtMTY5ZjNlYWZjZjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAxNTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTFlMmJjZTY1YjEwMzk5ZDc4YmRiZGYyMzM2MDc4MDdmZGI4NWJjYzkwNGM1OGYyMjNiMzhmZjgyODg3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUTh8hxFu9uFgzf7td4mWqYU51cDP9ktbVQ481bzK-U)
> 
> 如图所示，似乎存在版本兼容问题？

你好，刚刚发布了支持低vsc低版本的插件：0.0.2，现在可以插件市场下载了
